// Route constants to avoid hardcoded strings
export const ROUTES = {
  HOME: '/',
  COLLECTIONS: '/collections',
  COLLECTIONS_ALL: '/collections/all-products',
  COLLECTIONS_BESTSELLERS: '/collections/bestsellers',
  COLLECTIONS_SUN_CARE: '/collections/sun-care',
  COLLECTIONS_LIP_BALM: '/collections/lip-balm',
  COLLECTIONS_HAIRFALL: '/collections/hairfall',
  COLLECTIONS_HAIR_CARE_1: '/collections/hair-care-1',
  COLLECTIONS_ACNE: '/collections/acne',
  COLLECTIONS_PIGMENTATION: '/collections/pigmentation',
  COLLECTIONS_DULL_SKIN: '/collections/dull-skin',
  COLLECTIONS_DETAN: '/collections/detan',
  COLLECTIONS_DAMAGED_HAIR: '/collections/damaged-hair',
  PAGES_ABOUT: '/pages/about-us',
  POLICIES_TERMS: '/policies/terms-of-service',
  POLICIES_PRIVACY: '/policies/privacy-policy',
  POLICIES_SHIPPING: '/policies/shipping-policy',
  POLICIES_REFUND: '/policies/refund-policy',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: '/products/:id',
  PRODUCT_DETAIL_SLUG: '/products/:slug',
  PRODUCT_DETAIL_ID_SLUG: '/products/:id/:slug',
  CART: '/cart',
  CHECKOUT: '/checkout',
  SEARCH: '/search',
  PROFILE: '/profile',
  API_DEBUG: '/debug/api',
  TEST_PAGE: '/test',
  ANALYTICS: '/analytics',
  ORDER_SUCCESS: '/order-success',
} as const;